/* Command untuk take, use, dan drop */

del(X,[X|Tail],Tail).
del(X,[Y|Tail],[Y|Tail1]):- del(X,Tail,Tail1).

take(I) :- player(X,Y,S,Lp,H,T,W,L), length(L,5), !, write('Your inventory is full.').
take(I) :- I==water, player(X,Y,S,Lp,H,T,W,L), item1(XI,YI,'available','water'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item1(XI,YI,'available','water')),asserta(item1(XI,YI,'taken','water')).
take(I) :- I==water, player(X,Y,S,Lp,H,T,W,L), item2(XI,YI,'available','water'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item2(XI,YI,'available','water')),asserta(item2(XI,YI,'taken','water')).
take(I) :- I==water, player(X,Y,S,Lp,H,T,W,L), item3(XI,YI,'available','water'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item3(XI,YI,'available','water')),asserta(item3(XI,YI,'taken','water')).
take(I) :- I==food, player(X,Y,S,Lp,H,T,W,L), item4(XI,YI,'available','food'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item4(XI,YI,'available','food')),asserta(item4(XI,YI,'taken','food')).
take(I) :- I==food, player(X,Y,S,Lp,H,T,W,L), item5(XI,YI,'available','food'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item5(XI,YI,'available','food')),asserta(item5(XI,YI,'taken','food')).
take(I) :- I==food, player(X,Y,S,Lp,H,T,W,L), item6(XI,YI,'available','food'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item6(XI,YI,'available','food')),asserta(item6(XI,YI,'taken','food')).
take(I) :- I==food, player(X,Y,S,Lp,H,T,W,L), item7(XI,YI,'available','food'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item7(XI,YI,'available','food')),asserta(item7(XI,YI,'taken','food')).
take(I) :- I==medicine, player(X,Y,S,Lp,H,T,W,L), item8(XI,YI,'available','medicine'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item9(XI,YI,'available','medicine')),asserta(item8(XI,YI,'taken','medicine')).
take(I) :- I==medicine, player(X,Y,S,Lp,H,T,W,L), item9(XI,YI,'available','medicine'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item9(XI,YI,'available','medicine')),asserta(item9(XI,YI,'taken','medicine')).
take(I) :- I==radar, player(X,Y,S,Lp,H,T,W,L), item10(XI,YI,'available','radar'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item10(XI,YI,'available','radar')),asserta(item10(XI,YI,'taken','radar')).
take(I) :- I==bazooka, player(X,Y,S,Lp,H,T,W,L), item11(XI,YI,'available','bazooka'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item11(XI,YI,'available','bazooka')),asserta(item11(XI,YI,'taken','bazooka')).
take(I) :- I==bazooka, player(X,Y,S,Lp,H,T,W,L), item12(XI,YI,'available','bazooka'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item12(XI,YI,'available','bazooka')),asserta(item12(XI,YI,'taken','bazooka')).
take(I) :- I==bazooka, player(X,Y,S,Lp,H,T,W,L), item13(XI,YI,'available','bazooka'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item13(XI,YI,'available','bazooka')),asserta(item13(XI,YI,'taken','bazooka')).
take(I) :- I==bazooka, player(X,Y,S,Lp,H,T,W,L), item14(XI,YI,'available','bazooka'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item14(XI,YI,'available','bazooka')),asserta(item14(XI,YI,'taken','bazooka')).
take(I) :- I==bazooka, player(X,Y,S,Lp,H,T,W,L), item15(XI,YI,'available','bazooka'), \+(length(L,5)), X==XI, Y==YI, append([I],L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,W,L1)),!,write('You just took a(n) '),write(I),write('.\n'),retract(item15(XI,YI,'available','bazooka')),asserta(item15(XI,YI,'taken','bazooka')).
take(_) :- player(_,_,S,Lp,H,T,W,L),!, write('You haven\'t got any item in your proximity to take.\n').


use(I) :- player(X,Y,S,Lp,H,T,W,L), \+(member(I,L)),!,write('You don\'t have '),write(I),write(' to use.\n').
use(I) :- player(X,Y,S,Lp,H,T,W,L), I==food, member(I,L), H<85, H1 is H + 15, del(I,L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H1,T,W,L1)),!,write('You successfully increased your energy by 15 points.\n').
use(I) :- player(X,Y,S,Lp,H,T,W,L), I==water, member(I,L), T<85, T1 is T + 15, del(I,L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T1,W,L1)),!,write('You successfully increased your hydration by 15 points.\n').
use(I) :- player(X,Y,S,Lp,H,T,W,L), I==medicine, member(I,L), Lp<85, Lp1 is Lp + 15, del(I,L,L1), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),!,write('You successfully increased your health point by 15 points.\n').
use(I) :- player(X,Y,S,Lp,H,T,W,L), I==bazooka, member(I,L),!, retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp,H,T,1,L)), write('You now have a bazooka on your hand.\n').

drop(I) :- player(X,Y,S,Lp,H,T,W,L), \+(member(I,L)),!,write('You don\'t have '),write(I),write(' anyway. What do you want to drop?\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==water, item(XI,YI,'taken','water'), member(I,L),!, del(I,L,L1), retract(item(XI,YI,'taken','water')), asserta(item(X,Y,'available','water')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==water, item2(XI,YI,'taken','water'), member(I,L),!, del(I,L,L1), retract(item2(XI,YI,'taken','water')), asserta(item2(X,Y,'available','water')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==water, item3(XI,YI,'taken','water'), member(I,L),!, del(I,L,L1), retract(item3(XI,YI,'taken','water')), asserta(item3(X,Y,'available','water')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==food, item4(XI,YI,'taken','food'), member(I,L),!, del(I,L,L1), retract(item4(XI,YI,'taken','food')), asserta(item4(X,Y,'available','food')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==food, item5(XI,YI,'taken','food'), member(I,L),!, del(I,L,L1), retract(item5(XI,YI,'taken','food')), asserta(item5(X,Y,'available','food')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==food, item6(XI,YI,'taken','food'), member(I,L),!, del(I,L,L1), retract(item6(XI,YI,'taken','food')), asserta(item6(X,Y,'available','food')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==food, item7(XI,YI,'taken','food'), member(I,L),!, del(I,L,L1), retract(item7(XI,YI,'taken','food')), asserta(item7(X,Y,'available','food')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==medicine, item8(XI,YI,'taken','medicine'), member(I,L),!, del(I,L,L1), retract(item8(XI,YI,'taken','medicine')), asserta(item8(X,Y,'available','medicine')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==medicine, item9(XI,YI,'taken','medicine'), member(I,L),!, del(I,L,L1), retract(item9(XI,YI,'taken','medicine')), asserta(item9(X,Y,'available','medicine')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').
drop(I) :- player(X,Y,S,Lp,H,T,W,L), I==radar, item10(XI,YI,'taken','radar'), member(I,L),!, del(I,L,L1), retract(item10(XI,YI,'taken','radar')), asserta(item10(X,Y,'available','radar')), retract(player(X,Y,S,Lp,H,T,W,L)), asserta(player(X,Y,S,Lp1,H,T,W,L1)),write('You just dropped a(n) '),write(I),write('.\n').